SELECT f.JUDUL || ' adalah film dengan durasi terpendek yaitu ' || f.DURASI || ' Menit, yang ditonton dengan umur termuda, yaitu ' || 
       MIN(EXTRACT(YEAR FROM TO_DATE('2021-01-01', 'YYYY-MM-DD')) - EXTRACT(YEAR FROM m.TGL_LAHIR)) || ' Tahun' AS KETERANGAN
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
JOIN TRANSAKSI t ON j.ID_JADWAL = t.ID_JADWAL
JOIN MEMBER m ON t.ID_MEMBER = m.ID_MEMBER
WHERE f.DURASI = (SELECT MIN(DURASI) FROM FILM)
GROUP BY f.JUDUL, f.DURASI;

SELECT th.ID_THEATER AS NOMOR_TEATER, th.KELAS, COUNT(t.KODE_PEMESANAN) AS TOTAL_PEMAKAIAN
FROM THEATER th
JOIN JADWAL j ON th.ID_THEATER = j.ID_THEATER
JOIN TRANSAKSI t ON j.ID_JADWAL = t.ID_JADWAL
GROUP BY th.ID_THEATER, th.KELAS
HAVING COUNT(t.KODE_PEMESANAN) = (
    SELECT MAX(COUNT(KODE_PEMESANAN))
    FROM TRANSAKSI t2
    JOIN JADWAL j2 ON t2.ID_JADWAL = j2.ID_JADWAL
    GROUP BY j2.ID_THEATER
);

SELECT DISTINCT m.NAMA AS NAMA_MEMBER, 
       (EXTRACT(YEAR FROM TO_DATE('2021-01-01', 'YYYY-MM-DD')) - EXTRACT(YEAR FROM m.TGL_LAHIR)) AS UMUR
FROM MEMBER m
JOIN TRANSAKSI t ON m.ID_MEMBER = t.ID_MEMBER
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE f.JUDUL = 'Habibie Ainun 3'
  AND j.ID_THEATER IN (
      SELECT ID_THEATER 
      FROM THEATER 
      WHERE HARGA > (SELECT MAX(HARGA) FROM THEATER WHERE ID_THEATER = 'Teater 1')
  );
  
  SELECT f.JUDUL, th.HARGA
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
JOIN THEATER th ON j.ID_THEATER = th.ID_THEATER
WHERE th.HARGA = (SELECT MIN(HARGA) FROM THEATER)
   OR th.HARGA = (SELECT MAX(HARGA) FROM THEATER)
ORDER BY th.HARGA ASC;

SELECT f.JUDUL, COUNT(j.ID_JADWAL) AS JUMLAH_TAYANG
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
GROUP BY f.JUDUL
HAVING COUNT(j.ID_JADWAL) > (
    SELECT MIN(COUNT(ID_JADWAL))
    FROM JADWAL
    GROUP BY ID_FILM
);

SELECT j.ID_THEATER, f.JUDUL, COUNT(j.ID_JADWAL) AS JUMLAH_TAYANG
FROM JADWAL j
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE f.DURASI > 100
GROUP BY j.ID_THEATER, f.JUDUL
HAVING COUNT(j.ID_JADWAL) > (
    SELECT AVG(COUNT(ID_JADWAL))
    FROM JADWAL
    GROUP BY ID_THEATER, ID_FILM
);

SELECT DISTINCT m.NAMA AS NAMA_MEMBER, m.NO_HP, f.JUDUL
FROM MEMBER m
JOIN TRANSAKSI t ON m.ID_MEMBER = t.ID_MEMBER
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE m.NO_HP LIKE '081%'
  AND j.ID_THEATER IN (
      SELECT ID_THEATER 
      FROM THEATER 
      WHERE HARGA > 30000
  );